#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Color Pallete
border="#d3d6df"
alert="#bd2c40"

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output eDP --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1360x768 --rotate normal --right-of eDP
    nitrogen --restore &
    bspc monitor eDP -d 一 二 三 四 五
    bspc monitor HDMI-A-0  六 七 八 九 十
else
   bspc monitor -d 一 二 三 四 五 六 七 八 九 十
fi

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5

# Coloring
bspc config focused_border_color	$border
bspc config urgent_border_color 	$alert

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# For Rule Opened Application
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a URxvt desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Inkscape desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a code-oss desktop='^1'
bspc rule -a "VirtualBox Manager" desktop='^6'
bspc rule -a obs desktop='^4'

# For Polybar
#bash ~/.config/polybar/launch.sh --cuts
bash ~/.config/polybar/launch.sh

# Start MPD after polybar is running
mpd

# Reload dunst
~/.config/dunst/dtest

# Custom Script
export PATH=$PATH:~/Data/bin
export GOPATH=$HOME/.config/go
export NVM_DIR="$HOME/.nvm"
